version: '3.7'

volumes:
  postgres_data:
  static_data:
  media_data:

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    depends_on:
      - postgres
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    volumes:
      - .:/app
      - static_data:/app/static
      - media_data:/app/media
    ports:
      - "8001:8001"
    command: python manage.py runserver 0.0.0.0:8001
  postgres:
    image: postgres:11.2
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  nginx:
    build:
      context: .
      dockerfile: ./compose/local/nginx/Dockerfile
    ports:
      - "80:8000"
    volumes:
      - static_data:/app/static
      - media_data:/app/media
    depends_on:
      - django
