version: '3.7'

volumes:
  postgres_data:

services:
  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    depends_on:
      - postgres
    env_file:
      - ./.envs/.production/.postgres
    ports:
      - "8001:8001"
    command: gunicorn digital_asset_management_api.wsgi:application --bind 0.0.0.0:8001 --workers 3
  postgres:
    image: postgres:11.2
    env_file:
      - ./.envs/.production/.postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    ports:
      - "80:8000"
    depends_on:
      - django
